apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mssql-ad
spec:
 replicas: 1
 serviceName: "mssql-ad"
 selector:
  matchLabels:
   app: mssql-ad
 template:
  metadata:
   labels:
    app: mssql-ad
  spec:
   securityContext:
     fsGroup: 10001
   containers:
    - name: mssql-ad
      image: 'mcr.microsoft.com/mssql/server:2019-latest'
      ports:
        - containerPort: 1433
      env:
      - name: ACCEPT_EULA
        value: "Y" 
      - name: MSSQL_SA_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mssql-ad
            key: MSSQL_SA_PASSWORD
      - name: MSSQL_PID
        value: Evaluation
      - name: MSSQL_AGENT_ENABLED
        value: "true"
      volumeMounts:
      - name: mssqldb
        mountPath: /var/opt/mssql
      - name: data
        mountPath: /var/opt/mssql/userdata
      - name: logs
        mountPath: /var/opt/mssql/userlogs
      - name: mssqlconf
        mountPath: /var/opt/mssql/mssql.conf
        subPath: mssql.conf
      - name: krb5-conf
        mountPath: /etc/krb5.conf
        subPath: krb5.conf
   hostAliases:
    - ip: "192.168.100.10"
      hostnames:
       - "dc.demo.lcl"
       - "demo.lcl"
       - "demo"
   dnsPolicy: "None"
   dnsConfig:
     nameservers:
       - 192.168.100.10
     searches:
       - "demo.lcl"
       - "lcl"
   volumes:    
   - name: mssqldb
     persistentVolumeClaim:
       claimName: sql-ad-main
   - name: data
     persistentVolumeClaim:
       claimName: sql-ad-data 
   - name: logs
     persistentVolumeClaim:
       claimName: sql-ad-logs
   - name: mssqlconf
     configMap:
       name: mssqlconf
   - name: krb5-conf
     configMap:
       name: krb5-conf
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-ad
spec:
  type: LoadBalancer
  ports:
  - name: sql
    protocol: TCP
    port: 1433
    targetPort: 1433
  selector:
    statefulset.kubernetes.io/pod-name: mssql-ad-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-ad-main
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 35Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-ad-data
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 35Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-ad-logs
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 35Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mssqlconf
data:
  mssql.conf: |
    [network]
    kerberoskeytabfile = /var/opt/mssql/secrets/mssql.keytab
    privilegedadaccount = sqlsvc
    
    [filelocation]
    defaultdatadir = /var/opt/mssql/userdata
    defaultlogdir = /var/opt/mssql/userlog
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: krb5-conf
data:
  krb5.conf: |
    [libdefaults]
    default_realm = DEMO.LCL
    [realms]
    DEMO.LCL = {
        kdc = DC.demo.lcl
        admin_server = DC.demo.lcl
        default_domain = DEMO.LCL
    }

    [domain_realm]
    .demo.lcl = DEMO.LCL
    demo.lcl = DEMO.LCL
---
apiVersion: v1
data:
  MSSQL_SA_PASSWORD: UGFzc3cwcmQ=
kind: Secret
metadata:
  name: mssql-ad
type: Opaque